// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4089.Stealth2017.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4089.Stealth2017.Robot;
import org.usfirst.frc4089.Stealth2017.RobotMap;

import com.ctre.CANTalon.TalonControlMode;

/**
 *
 */
public class UserDrive extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public UserDrive() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	/*need to exit Motion Profiling Mode when user is driving*/
    	RobotMap.driveLeftMotor1.changeControlMode(TalonControlMode.Voltage);
    	RobotMap.driveRightMotor1.changeControlMode(TalonControlMode.Voltage);
    	//TODO need to MPLeft.reset();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	System.out.print("Left Encoder: ");
    	System.out.print(-RobotMap.driveLeftMotor1.getEncPosition());
    	System.out.print(" Right Encoder ");
    	System.out.println(RobotMap.driveRightMotor1.getEncPosition());
    	System.out.print(" Right Encoder Velocity ");
    	System.out.print(RobotMap.driveRightMotor1.getEncVelocity());
    	System.out.print(" Left Encoder Velocity ");
    	System.out.println(RobotMap.driveLeftMotor1.getEncVelocity());
    	System.out.println("Angle" + RobotMap.digitalSPIGyro.getAngle());
    	System.out.print("Rate" + RobotMap.digitalSPIGyro.getRate());
    	/*System.out.print(" Right Encoder Pulse Width Velocity ");
    	System.out.print(RobotMap.driveRightMotor1.getPulseWidthVelocity());
    	System.out.print(" Left Encoder Pulse Width Velocity ");
    	System.out.println(RobotMap.driveLeftMotor1.getPulseWidthVelocity());*/
    	Robot.drive.operatorDrive(Robot.oi.getDriveStick());
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
